
[[task_throw,throw]]
=== throw ===

A task to re-throw a previously thrown exception. 

--------------------------------------
<c:trycatch>
  <try>
     <fail message="houston,.."/> 
  </try>
  <catch>
    <echo level="DEBUG">*** exception seen ***</echo>
    <c:throw />
  </c:catch>
</c:trycatch>
--------------------------------------


==== Attributes ====
[cols="15%,15%,20%,50%"]
|===========================
| Attribute | Type | Default | Description 
| `reference` | string | `trycatch.object` |  The name of the reference holding the previously thrown exception 
| `var` | string | `trycatch.object` | An alias for attribute `reference` 
|===========================

==== Behaviour ====

When this task is executed, it looks-up whether the current project contains a specific reference. By default, the name of that reference is `trycatch.object`. The name of this reference can be changed  by using attribute `reference`. If that reference exists and an exception is attached with that reference, then that exception is thrown. Otherwise, a standard build exception is generated and thrown. In that case, `throw` acts like Ant\'s standard task `fail`.

Note that `throw` works in any context. Consider

--------------------------------------
<c:trycatch>
 <try> 
   <fail message="houston,.." />
 </try>
 ; ignores build exception
 <catch />
</c:trycatch>
..
; very much later
.. 
; throws build exception 'houston,..'  
<c:throw />
--------------------------------------

